Lesson 2
AlexeyTretyakov98/if-js pull request #2
Opened 2022-05-02 10:04 UTC by AlexeyTretyakov98

2022-05-04 13:46 UTC, Marinarium requested changes

2022-05-04 13:46 UTC, Marinarium commented on package.json
> +    "prettier": "prettier --write *.js",
Fix, **prettier doesn't work** for js files inside js folder

2022-05-04 13:46 UTC, Marinarium commented on js/main.js
> + console.log(typeof test);
приведите test к типу bool;

please finish this part

[link](https://learn.javascript.ru/type-conversions)

2022-05-04 13:46 UTC, Marinarium commented on js/main.js
> +     result = result + arrThree[i]
С помощью цикла for найдите **произведение** элементов этого массива.
У тебя сумма

2022-05-05 13:32 UTC, AlexeyTretyakov98 commented on js/main.js
> + console.log(typeof test);
console.log(Boolean(test));

2022-05-05 13:32 UTC, AlexeyTretyakov98 commented on js/main.js
> +     result = result + arrThree[i]
fix

2022-05-05 13:36 UTC, AlexeyTretyakov98 commented on package.json
> +    "prettier": "prettier --write *.js",
add *.html

2022-05-11 07:48 UTC, merged